In [5]:
subjects = ['Math', 'Physics', 'Computer Science','Chemistry']
for subs in subjects:
  print(subs)

Math
Physics
Computer Science
Chemistry


In [6]:
print(subjects[2])

Computer Science


In [7]:
subjects[1:]

['Physics', 'Computer Science', 'Chemistry']

In [14]:
scientist = {'Name': 'Allan Turing','Field': 'Mathematics'}
print('Name:',scientist['Name'])

Name: Allan Turing


In [17]:
scientist = {'Name': 'Allan Turing','Field': 'Mathematics'}
print('Field:',scientist['Field'])

Field: Mathematics


In [22]:
if 'Computer Science' in subjects:
  print('Computer Science in Subject')
elif 'Comsci' in subjects:
  print('Yes')
else:
  print('No Subject')

Computer Science in Subject


In [24]:
import numpy as np

x=np.array([1,2,3])
print(x)

[1 2 3]


In [28]:
a=np.zeros([2,2])
print(a)             

[[0. 0.]
 [0. 0.]]


In [31]:
b=np.ones([2,2])
print(b)

[[1. 1.]
 [1. 1.]]


In [32]:
c=np.random.randint(10, size=(5))
d=c*c
print(c)

[0 4 1 8 1]


In [33]:
c=np.random.randint(10, size=(5))
d=c*c
print(d)

[1 1 1 4 4]


In [40]:
x=np.array([1,2,3])
y=np.array([4,5,6])
add=x+y
sub=x-y
print(add)
print(sub)

[5 7 9]
[-3 -3 -3]


In [41]:
MaxvalX = np.argmax(x)
MaxvalY = np.argmax(y)
print(MaxvalX)
print(MaxvalY)

2
2


In [42]:
print(x>y)
print(x==y)

[False False False]
[False False False]


In [45]:
x = np.array([[1,2,3],[4,5,6]])
print(np.sum(x))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))

21
[5 7 9]
[ 6 15]


In [115]:
#-----------------EXERCISE--------------------
import numpy as np

A = np.matrix([[22,5,16,9],[13,20,19,0],[5,9,1,16],[27,13,15,19]])
print(A)


[[22  5 16  9]
 [13 20 19  0]
 [ 5  9  1 16]
 [27 13 15 19]]


In [67]:
B = np.matrix([[10,5,20,20],[5,21,22,27],[26,19,22,3],[27,8,18,7]])
print(B)

[[10  5 20 20]
 [ 5 21 22 27]
 [26 19 22  3]
 [27  8 18  7]]


In [80]:
c = np.array ([24,3,17,7,11,2,21,2,24,18,3,11,14,25,2,20])
print(c)

[24  3 17  7 11  2 21  2 24 18  3 11 14 25  2 20]


In [81]:
d = np.array([3,15,24,22,19,24,4,29,6,3,20,1,11,25,26,6])
print(d)

[ 3 15 24 22 19 24  4 29  6  3 20  1 11 25 26  6]


In [116]:
#1
np.add(A,B)

matrix([[ 158,   25,   64,   81],
        [  97,   96,   83, -108],
        [ -59,    5,  -79,  132],
        [ 135,   85,   63,  143]])

In [117]:
#2
np.subtract(A,B)

matrix([[-114,  -15,  -32,  -63],
        [ -71,  -56,  -45,  108],
        [  69,   13,   81, -100],
        [ -81,  -59,  -33, -105]])

In [118]:
#3
np.multiply(A,B)

matrix([[2992,  100,  768,  648],
        [1092, 1520, 1216,    0],
        [-320,  -36,  -80, 1856],
        [2916,  936,  720, 2356]])

In [119]:
#4
np.matmul(A,B)

matrix([[3360, 1404,  528, 4016],
        [2232, 1704,  384,  980],
        [3100, 1932, 1504, 1488],
        [5856, 2836, 1840, 4636]])

In [76]:
#5
add = c+d
print(add)

[24, 3, 17, 7, 11, 2, 21, 2, 24, 18, 3, 11, 14, 25, 2, 20, 3, 15, 24, 22, 19, 24, 4, 29, 6, 3, 20, 1, 11, 25, 26, 6]


In [82]:
#6
sub = c-d
print(sub)

[ 21 -12  -7 -15  -8 -22  17 -27  18  15 -17  10   3   0 -24  14]


In [83]:
#7
multiply = c * d
print(multiply)


[ 72  45 408 154 209  48  84  58 144  54  60  11 154 625  52 120]


In [111]:
#8
mul = np.dot(c,d)
print(mul)


2298


In [120]:
#9
add_A = A+10
print(add_A)

[[32 15 26 19]
 [23 30 29 10]
 [15 19 11 26]
 [37 23 25 29]]


In [122]:
#10
add_B = B+10
print(add_B)

[[146  30  58  82]
 [ 94  86  74 -98]
 [-54   6 -70 126]
 [118  82  58 134]]


In [91]:
#11
add_C = c + 15
print(add_C)

[39 18 32 22 26 17 36 17 39 33 18 26 29 40 17 35]


In [92]:
#12
add_D = d + 15
print(add_D)

[18 30 39 37 34 39 19 44 21 18 35 16 26 40 41 21]


In [123]:
#13
S = (2 * A) + (2 * B)
print (S)

[[ 316   50  128  162]
 [ 194  192  166 -216]
 [-118   10 -158  264]
 [ 270  170  126  286]]


In [124]:
#14
J = (A + B) * 3
print(J)

[[ 474   75  192  243]
 [ 291  288  249 -324]
 [-177   15 -237  396]
 [ 405  255  189  429]]


In [126]:
#15
B = (A - B + A -B +B) * 4
print(B)

[[ 1648   200   384   936]
 [ 1032   736   568 -1728]
 [-1144  -280 -1304  1472]
 [ 1080   840   408  1528]]
